 Household_Data <- read.table(data_file,header = TRUE,sep = ";",stringsAsFactors=FALSE,dec = ".")
 sub_data <- Household_Data[Household_Data$Date %in% c("1/2/2007","2/2/2007"),]
Date_Time <- strptime(paste(sub_data$Date,sub_data$Time,sep = " "),"%d/%m/%Y %H:%M:%S")
 Global_Active_Power <- as.numeric(sub_data$Global_active_power)
voltage <- as.numeric(sub_data$Voltage)
Global_Reactive_Power <- as.numeric(sub_data$Global_reactive_power)
png("plot4.png", width=480, height=480)
par(mfrow = c(2,2))
plot(Date_Time,Global_Active_Power,type = "l",xlab="", ylab="Global Active Power", cex=0.2)
plot(Date_Time,voltage,type = "l",xlab="datetime",ylab = "Voltage")
plot(Date_Time,Sub_metering1,type = "l",ylab = "Energy Submetering",xlab = "")
lines(Date_Time,Sub_metering2,type = "l", col = "red")
lines(Date_Time,Sub_metering3,type = "l", col = "blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = 1, lwd = 2.5,col = c("black","red","blue"))
plot(Date_Time,Global_Reactive_Power,type = "l",xlab = "datetime",ylab = "Global_reactive_power")
dev.off()